### ISSUE TITLE
Building: "Failed to collect configuration for /". (Maybe some misunderstood with config)

### ISSUE THREAD

**Issue by t-lessy** [spaceness/stardust#24]
When building with `pnpm build`:
```sh
. . .
   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
   Collecting page data  ...Error: Failed to collect configuration for /
    at <unknown> (/home/z/oh.service/stardust/node_modules/.pnpm/next@15.0.3-canary.5_babel-plugin-react-compiler@19.0.0-beta-6fc168f-20241025_react-dom@19.0._7sijss3hwiiec5lspbh6skabty/node_modules/next/dist/build/utils.js:1131:23)
    at async Span.traceAsyncFn (/home/z/oh.service/stardust/node_modules/.pnpm/next@15.0.3-canary.5_babel-plugin-react-compiler@19.0.0-beta-6fc168f-20241025_react-dom@19.0._7sijss3hwiiec5lspbh6skabty/node_modules/next/dist/trace/trace.js:153:20) {
  [cause]: TypeError: Cannot use 'in' operator to search for 'auth0' in undefined
      at 7091 (/home/z/oh.service/stardust/.next/server/chunks/5137.js:1:22778)
      at t (/home/z/oh.service/stardust/.next/server/webpack-runtime.js:1:142)
      at 28855 (/home/z/oh.service/stardust/.next/server/chunks/5137.js:1:23082)
      at t (/home/z/oh.service/stardust/.next/server/webpack-runtime.js:1:142)
      at 44318 (/home/z/oh.service/stardust/.next/server/chunks/5137.js:1:15155)
      at Function.t (/home/z/oh.service/stardust/.next/server/webpack-runtime.js:1:142)
      at async getLayoutOrPageModule (/home/z/oh.service/stardust/node_modules/.pnpm/next@15.0.3-canary.5_babel-plugin-react-compiler@19.0.0-beta-6fc168f-20241025_react-dom@19.0._7sijss3hwiiec5lspbh6skabty/node_modules/next/dist/server/lib/app-dir-module.js:33:15)
      at async collectAppPageSegments (/home/z/oh.service/stardust/node_modules/.pnpm/next@15.0.3-canary.5_babel-plugin-react-compiler@19.0.0-beta-6fc168f-20241025_react-dom@19.0._7sijss3hwiiec5lspbh6skabty/node_modules/next/dist/build/segment-config/app/app-segments.js:50:45)
      at async (/home/z/oh.service/stardust/node_modules/.pnpm/next@15.0.3-canary.5_babel-plugin-react-compiler@19.0.0-beta-6fc168f-20241025_react-dom@19.0._7sijss3hwiiec5lspbh6skabty/node_modules/next/dist/build/utils.js:1129:28)
}
. . .
```

Sorry if I mistaken in config file, I am not experienced with Cloudflare and Postgres. I'll add it below. 😅
All instructions were clearly, except for config.json. I hadn't Cloudflare account, and app did not build without Turnstile configuration. Then I tried to register to obtain tokens. I also can't understand which "JWT token" in auth->secret do I need to work with Stardust. Only token I tried is Cloudflare account token with "Read all" permission.

```json
{
	"$schema": "config-schema.json",
	"databaseUrl": "postgresql://user:pass@localhost:1234",
	"metadataUrl": "example.com:8080",
	"docker": {
		"type": "socket",
		"socket": "/var/run/docker.sock",
		"network": "stardust"
	},
	"auth": {
		"secret": "very_secret",
		"turnstile": {
			"secret": "very_secret",
			"siteKey": "very_secret",
			"hosts": "example.com"
		},
		"credentials": true,
		"oauth": "undefined"
	},
	"session": {
		"keepaliveDuration": "1440"
	}
}
```

All good to devs, contributors and issuers! Sorry again if I got bad with config. 🦊

**Comment by t-lessy** [comment]
Oh, it worked! Thanks! ☺️
